"""add avatar and verified field to user

Revision ID: 5ad4da56701a
Revises: c5f91d24fef3
Create Date: 2025-03-10 10:21:14.116953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad4da56701a'
down_revision: Union[str, None] = 'c5f91d24fef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('avatar', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
