"""users

Revision ID: c5f91d24fef3
Revises: 891c79e22a29
Create Date: 2025-02-28 21:12:37.454019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f91d24fef3'
down_revision: Union[str, None] = '891c79e22a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

roles = sa.Enum('admin', 'moderator', 'user', name='role')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    roles.create(op.get_bind(), checkfirst=True)
    op.add_column("users", sa.Column("role", roles, nullable=True))
    
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('contacts', 'additional_info',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key('fk_user', 'contacts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user', 'contacts', type_='foreignkey')
    op.alter_column('contacts', 'additional_info',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('contacts', 'user_id')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_table('users')
    sa.Enum(name="role").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
